documents = [
    # SELECT and filtering
    "The SELECT statement retrieves data from one or more tables. The basic syntax is: SELECT column1, column2 FROM table_name. To retrieve all columns, use SELECT *. You can filter results using the WHERE clause, e.g. SELECT * FROM students WHERE age > 18.",
    "The WHERE clause filters rows based on a condition. Common operators include =, !=, <, >, <=, >=, LIKE, IN, BETWEEN, and IS NULL. Example: SELECT name FROM employees WHERE department = 'Sales' AND salary > 50000.",
    "The LIKE operator is used for pattern matching in WHERE clauses. The % wildcard matches any sequence of characters, and _ matches exactly one character. Example: SELECT * FROM products WHERE name LIKE 'A%' returns all products whose name starts with 'A'.",
    "The ORDER BY clause sorts query results. Use ASC for ascending (default) or DESC for descending order. Example: SELECT name, salary FROM employees ORDER BY salary DESC returns employees sorted from highest to lowest salary.",
    "The LIMIT clause restricts the number of rows returned. Example: SELECT * FROM orders ORDER BY order_date DESC LIMIT 10 returns the 10 most recent orders. In SQL Server the equivalent syntax is TOP: SELECT TOP 10 * FROM orders.",
    "The DISTINCT keyword removes duplicate rows from results. Example: SELECT DISTINCT department FROM employees returns each department name only once, even if many employees share the same department.",

    # Aggregation
    "Aggregate functions perform calculations on a set of rows and return a single value. Common aggregate functions are COUNT(), SUM(), AVG(), MIN(), and MAX(). Example: SELECT AVG(salary) FROM employees calculates the average salary across all employees.",
    "The GROUP BY clause groups rows that share the same value in one or more columns, typically used with aggregate functions. Example: SELECT department, AVG(salary) FROM employees GROUP BY department calculates the average salary per department.",
    "The HAVING clause filters groups produced by GROUP BY, similar to how WHERE filters rows. Example: SELECT department, COUNT(*) FROM employees GROUP BY department HAVING COUNT(*) > 5 returns only departments with more than 5 employees. HAVING is evaluated after grouping; WHERE is evaluated before.",
    "COUNT(*) counts all rows including NULLs, while COUNT(column_name) counts only non-NULL values in that column. Example: SELECT COUNT(*) FROM orders counts all orders, while SELECT COUNT(shipped_date) FROM orders counts only orders that have a shipped date.",

    # JOINs
    "A JOIN combines rows from two or more tables based on a related column. The most common type is INNER JOIN, which returns only rows where the join condition is met in both tables. Example: SELECT orders.id, customers.name FROM orders INNER JOIN customers ON orders.customer_id = customers.id.",
    "A LEFT JOIN (or LEFT OUTER JOIN) returns all rows from the left table and matching rows from the right table. If there is no match, NULL values are returned for the right table's columns. This is useful when you want to keep all records from one table even if there is no match.",
    "A RIGHT JOIN returns all rows from the right table and matching rows from the left table. NULLs fill in where there is no match on the left side. It is the mirror image of a LEFT JOIN.",
    "A FULL OUTER JOIN returns all rows from both tables. Where there is no match on either side, NULLs are used. This is useful for finding records that exist in one table but not the other.",
    "A CROSS JOIN returns the Cartesian product of two tables, meaning every row from the first table is paired with every row from the second. If table A has 3 rows and table B has 4 rows, the result has 12 rows. It is rarely used intentionally but is important to understand.",
    "A self-join joins a table with itself. This is useful for comparing rows within the same table. Example: SELECT a.name, b.name FROM employees a JOIN employees b ON a.manager_id = b.id finds each employee and their manager's name.",

    # Subqueries
    "A subquery is a query nested inside another query. It can appear in the SELECT, FROM, or WHERE clause. Example: SELECT name FROM employees WHERE salary > (SELECT AVG(salary) FROM employees) returns employees who earn above average.",
    "A correlated subquery references a column from the outer query and is executed once for each row of the outer query. Example: SELECT name FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE department = e.department) finds employees who earn above their own department's average.",
    "The EXISTS operator tests whether a subquery returns any rows. It returns TRUE if the subquery produces at least one row, and FALSE otherwise. Example: SELECT name FROM customers WHERE EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.id) returns only customers who have placed at least one order.",
    "The IN operator checks whether a value matches any value in a list or subquery result. Example: SELECT name FROM students WHERE id IN (SELECT student_id FROM enrollments WHERE course = 'Databases') returns students enrolled in the Databases course.",

    # Keys and constraints
    "A primary key uniquely identifies each row in a table. It must contain unique values and cannot be NULL. A table can have only one primary key, which can consist of a single column or multiple columns (composite primary key). Example: CREATE TABLE students (id INT PRIMARY KEY, name VARCHAR(100)).",
    "A foreign key is a column (or set of columns) in one table that references the primary key of another table. It enforces referential integrity, ensuring that a value in the foreign key column must exist in the referenced table. Example: orders.customer_id is a foreign key referencing customers.id.",
    "A UNIQUE constraint ensures all values in a column are distinct. Unlike a primary key, a table can have multiple UNIQUE constraints, and UNIQUE columns can contain NULL values (though only one NULL is allowed per column in most databases). Example: CREATE TABLE users (email VARCHAR(100) UNIQUE).",
    "A NOT NULL constraint prevents a column from storing NULL values. If you try to insert a row without providing a value for a NOT NULL column, the database returns an error. Example: CREATE TABLE products (name VARCHAR(100) NOT NULL, price DECIMAL NOT NULL).",
    "A CHECK constraint enforces a condition that all values in a column must satisfy. Example: CREATE TABLE employees (age INT CHECK (age >= 18)) ensures no employee younger than 18 can be inserted.",
    "A DEFAULT constraint provides a default value for a column when no value is explicitly inserted. Example: CREATE TABLE orders (status VARCHAR(20) DEFAULT 'pending') means new orders automatically get the status 'pending' if none is specified.",

    # Normalisation
    "Normalization is the process of organizing a relational database to reduce redundancy. It involves decomposing tables and defining relationships. The goal is that each piece of data is stored in exactly one place.",
    "First Normal Form (1NF) requires that each column contains atomic (indivisible) values, and each row is unique. A table violates 1NF if a column stores multiple values, for example storing 'Math, Science' in a single 'subjects' column instead of using separate rows.",
    "Second Normal Form (2NF) requires the table to be in 1NF and that every non-key column is fully dependent on the entire primary key. A violation occurs when a column depends on only part of a composite primary key. Fixing 2NF violations involves splitting the table.",
    "Third Normal Form (3NF) requires the table to be in 2NF and that no non-key column depends on another non-key column (no transitive dependency). Example: if a table stores employee_id, department_id, and department_name, department_name depends on department_id, not on employee_id, which is a transitive dependency and violates 3NF.",
    "Denormalization is the intentional introduction of redundancy into a database design for performance reasons. By storing redundant data, queries can avoid expensive joins. It is a trade-off: faster reads at the cost of update anomalies and increased storage.",

    # Indexes
    "An index is a data structure that improves the speed of data retrieval. Without an index, the database performs a full table scan to find rows matching a query. With an index on the searched column, the lookup is much faster. Example: CREATE INDEX idx_salary ON employees(salary).",
    "A clustered index determines the physical order in which rows are stored on disk. A table can only have one clustered index. In most databases, the primary key is automatically a clustered index. The leaf nodes of a clustered index contain the actual row data.",
    "A non-clustered index stores a separate structure with pointers back to the actual rows. A table can have multiple non-clustered indexes. They speed up queries but add overhead to INSERT, UPDATE, and DELETE operations because the index must also be updated.",
    "Indexes improve read performance but slow down write performance. Each INSERT, UPDATE, or DELETE must also update all indexes on the table. Over-indexing (adding indexes on every column) can therefore hurt overall performance, especially on tables with frequent writes.",

    # Transactions
    "A transaction is a sequence of SQL operations treated as a single unit of work. It either completes fully (COMMIT) or is entirely undone (ROLLBACK). Transactions ensure that the database moves from one consistent state to another, even if an error occurs mid-way.",
    "ACID is an acronym describing four properties that guarantee reliable transactions. Atomicity: all operations in a transaction succeed or none do. Consistency: a transaction brings the database from one valid state to another. Isolation: concurrent transactions do not interfere with each other. Durability: once committed, changes persist even after a crash.",
    "The COMMIT statement permanently saves all changes made during the current transaction. Once committed, the changes are visible to other users and cannot be undone with ROLLBACK. Example workflow: BEGIN TRANSACTION; UPDATE accounts SET balance = balance - 100 WHERE id = 1; UPDATE accounts SET balance = balance + 100 WHERE id = 2; COMMIT.",
    "The ROLLBACK statement undoes all changes made during the current transaction, restoring the database to the state it was in before the transaction began. It is used when an error is detected mid-transaction. Example: if a bank transfer fails halfway, ROLLBACK ensures neither account is changed.",

    # Views and CTEs
    "A VIEW is a stored query that acts like a virtual table. It does not store data itself but presents the result of a SELECT statement. Views simplify complex queries, enforce security by restricting column access, and provide a consitent interface even when the underlying table structure changes.",
    "A Common Table Expression (CTE) is a named temporary result set defined with the WITH keyword, used within a single query. CTEs improve readability by breaking complex queries into named steps. Example: WITH high_earners AS (SELECT * FROM employees WHERE salary > 80000) SELECT department, COUNT(*) FROM high_earners GROUP BY department.",
    "A recursive CTE references itself and is used to query hierarchical data, such as organizational charts or category trees. It consists of an anchor member (base case) and a recursive member. Example: traversing a manager/employee hierarchy to find all reports under a given manager.",

    # DDL
    "DDL (Data Definition Language) statements define and modify the structure of database objects. Key DDL statements are CREATE (create a new table or object), ALTER (modify an existing object), DROP (permanently delete an object), and TRUNCATE (remove all rows from a table without logging individual row deletions).",
    "The CREATE TABLE statement defines a new table and its columns. Example: CREATE TABLE students (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL, grade CHAR(1), enrolled_date DATE DEFAULT CURRENT_DATE). Column definitions include the data type and optional constraints.",
    "The ALTER TABLE statement modifies an existing table structure. You can add a column (ALTER TABLE t ADD COLUMN new_col INT), drop a column (ALTER TABLE t DROP COLUMN old_col), rename a column, or add/drop constraints. ALTER TABLE does not affect existing data unless the change is incompatible.",
    "DROP TABLE permanently removes a table and all its data from the database. This cannot be undone. TRUNCATE TABLE removes all rows but keeps the table structure intact and is faster than DELETE for large tables because it does not log individual row deletions.",

    # Entity-Relationship Modelling
    # ERM Concepts
    "The Entity-Relationship Model (ERM) is a conceptual data model used in the analysis and design phase of database development. It describes the structure of a domain using entities (objects), attributes (properties), and relationships (associations between entities). An ER diagram (ERD) is the visual representation of this model.",
    "An entity is a representation of a distinguishable real-world object, such as a specific customer or a specific product. An entity set (entity type) is the collection of all similar entities, such as all customers or all products. In an ER diagram, entity sets are drawn as rectangles.",
    "An attribute describes a property that all entities in an entity set share. Each entity has a specific attribute value. For example, the entity set 'Customer' might have the attributes CustomerID, Name, and Email. Attributes are drawn as ovals connected to their entity set.",
    "Attributes are classified by their structure. Simple (atomic) attributes hold a single indivisible value, such as a birth date. Composite attributes can be broken into smaller parts, such as an address split into street, city, and postal code. Multivalued attributes can hold multiple values simultaneously (e.g. a list of email addresses) and are drawn with a double oval. Derived attributes are computed from other attributes (e.g. age derived from birth date) and are drawn with a dashed oval.",
    "A candidate key is a minimal set of attributes that uniquely identifies every entity in an entity set. It must be unique, irreducible (no attribute can be removed without losing uniqueness), and mandatory (never NULL). A primary key is the chosen candidate key for a relation. Secondary keys are the remaining candidate keys.",
    "A relationship describes an interaction or association between two or more entity sets. Relationships are expressed as verbs (e.g. 'Customer places Order'). They are drawn as diamonds in Chen notation. Relationships can themselves have attributes, such as the 'order date' on a 'places' relationship.",
    "Cardinality defines how many entities on one side of a relationship can be associated with entities on the other side. The three basic cardinalities are: 1:1 (one-to-one), 1:N (one-to-many), and N:M (many-to-many). Example: one department employs many employees (1:N); one student enrolls in many courses and each course has many students (N:M).",
    "Participation (optionality) specifies whether every entity must take part in a relationship or whether participation is optional. Total participation (mandatory) means every entity must be in at least one relationship instance. Partial participation (optional) means an entity may exist without being in that relationship. In Crow's Foot notation this is shown with a circle (optional) or a vertical bar (mandatory) near the entity.",
    "Crow's Foot notation (also called entity-relationship notation or IE notation) is a compact, practical ERD style widely used in modelling tools. Entities are shown as rectangles listing their attributes. Cardinality and optionality are shown at each end of a relationship line using symbols: a crow's foot (three lines) for 'many', a single line for 'one', a circle for 'zero/optional', and a vertical bar for 'one/mandatory'. Example: a line ending in circle-crow's-foot means 'zero or many'.",
    "Chen notation is the original ERD style. Entity sets are rectangles, relationships are diamonds, and attributes are ovals. Cardinalities are written as numbers or letters (1, N, M) on the relationship lines. Chen notation is powerful because it supports multivalued and composite attributes explicitly, but it can become cluttered for large models.",
    "Identifying relationships occur when the primary key of the child entity set includes the primary key of the parent entity set. The child cannot exist without the parent. In Crow's Foot notation this is shown with a solid relationship line and a mandatory symbol on the child side. Non-identifying relationships are the standard: the parent's primary key appears only as a foreign key in the child, and the child can exist independently.",
    "The three-schema architecture (ANSI/SPARC) describes three levels of database abstraction: the external level (user views), the conceptual level (the ER diagram representing the entire enterprise), and the internal/physical level (actual storage structures and indexes). ERDs operate at the conceptual level and are technology-independent.",

    # Relational Data Modelling
    "A relation in the relational model is a set of tuples (rows) that share the same schema. Formally, a relation R over attributes A1, A2, ..., An is a subset of the Cartesian product dom(A1) × dom(A2) × ... × dom(An). The degree of a relation is the number of attributes; the cardinality is the number of tuples. Because a relation is a set, it contains no duplicate tuples and has no defined row order.",
    "A relation schema describes the structure of a relation: its name and the list of its attributes with their domains. Notation: Relation(Attribute1, Attribute2, ..., AttributeN). Example: Customer(CustomerID, LastName, FirstName, City). The primary key attribute(s) are typically underlined in the schema notation.",
    "Integrity rules ensure data quality in the relational model. Entity integrity: every relation must have a primary key, and no part of the primary key may be NULL. Referential integrity: every foreign key value must match an existing primary key value in the referenced relation, or be NULL if the relationship is optional. Domain integrity: every attribute value must belong to the defined domain of that attribute.",
    "A surrogate key is an artificially generated primary key with no business meaning, typically an auto-incremented integer. Surrogate keys are preferred over natural (business) keys when natural keys are long, composite, or subject to change. For example, using a CustomerID integer instead of an email address as the primary key avoids cascading updates if the email changes.",
    "Mapping rule for entity sets: each entity set in an ER diagram becomes a relation. The attributes of the entity set become the attributes of the relation. The primary key of the entity set becomes the primary key of the relation. Example: the entity set Student(MatrNr, Name, Programme) maps directly to a relation Student(MatrNr, Name, Programme).",
    "Mapping rule for 1:N relationships: the foreign key is placed on the N-side of the relationship. It references the primary key of the 1-side relation. Example: if one Department employs many Employees, the Employee relation gets a DepartmentID foreign key referencing Department(DepartmentID). Attributes of the relationship itself are also added to the N-side relation.",
    "Mapping rule for N:M relationships: a new junction (association) relation is created. Its primary key is a composite key made up of the primary keys of both participating entity sets. Any attributes of the relationship itself become attributes of the junction relation. Example: a Student enrolls in many Courses and each Course has many Students → Enrollment(StudentID, CourseID, EnrollmentDate).",
    "Mapping rule for 1:1 relationships: the foreign key can be placed on either side. It is usually placed on the side with partial (optional) participation to allow NULL. A UNIQUE constraint is added to the foreign key column to enforce the one-to-one constraint. If both sides are mandatory, the two entity sets can often be merged into one relation.",
    "Multivalued attributes cannot be stored directly in a relation (this would violate 1NF). They are resolved by creating a separate relation containing the primary key of the original entity set and one row per value of the multivalued attribute. Example: if a Customer can have multiple phone numbers, create PhoneNumber(CustomerID, PhoneNumber) with a composite primary key.",

    # Relational Algebra
    "Relational algebra is a formal query language for the relational model. It provides a set of operations that take one or two relations as input and produce a new relation as output. This closure property means operations can be nested and composed. SQL queries can be mapped to relational algebra expressions, which is how database engines optimise them.",
    "Selection (σ) filters tuples from a relation based on a predicate. Only tuples satisfying the condition are included in the result. Notation: σ_condition(R). Example: σ_(salary > 50000)(Employee) returns all tuples from Employee where salary exceeds 50000. Selection is equivalent to the SQL WHERE clause.",
    "Projection (π) selects a subset of attributes (columns) from a relation. Notation: π_A1,A2,...(R). Duplicate tuples in the result are eliminated (since the result is a set). Example: π_(name, department)(Employee) returns only the name and department columns. Projection is equivalent to the column list in a SQL SELECT statement.",
    "The Cartesian product (×) of two relations R and S combines every tuple of R with every tuple of S. If R has m tuples and S has n tuples, the result has m×n tuples. Notation: R × S. The result contains all attributes of both relations. The Cartesian product is rarely useful alone but forms the basis for joins.",
    "A Join (⋈) combines tuples from two relations that satisfy a join condition. It is equivalent to a Cartesian product followed by a selection. An Equi-Join uses the equality operator (=) on a shared attribute. A Theta-Join allows any comparison operator (=, <, >, ≤, ≥, ≠). A Natural Join automatically joins on all attributes with the same name and eliminates duplicate columns. Notation: R ⋈_condition S.",
    "Set operations in relational algebra require both relations to be union-compatible (same number of attributes with matching domains). Union (R ∪ S) returns all tuples appearing in R or S (duplicates removed). Intersection (R ∩ S) returns only tuples appearing in both R and S. Difference (R − S) returns tuples in R that do not appear in S.",
    "Division (R ÷ S) is a relational algebra operation used to answer 'for all' queries. R ÷ S returns the tuples from R that are associated with every tuple in S. Example: given a relation EnrolledIn(StudentID, CourseID) and a relation AllCourses(CourseID), EnrolledIn ÷ AllCourses returns the StudentIDs of students enrolled in every course. Division has no direct SQL equivalent but can be expressed using NOT EXISTS.",

    # Functional Dependencies and Extended Normalization
    "A functional dependency (FD) X → Y means that the values of attribute set X uniquely determine the values of attribute set Y. For any two tuples in the relation, if they agree on X they must also agree on Y. Example: in an Employee table, EmployeeID → {Name, Department, Salary} because each employee ID maps to exactly one name, department, and salary.",
    "A full functional dependency means Y is functionally dependent on X, and Y is not functionally dependent on any proper subset of X. If removing any attribute from X breaks the dependency, then X is irreducible. Partial dependencies (where Y depends on only part of a composite key) are the root cause of 2NF violations.",
    "A transitive dependency occurs when X → Y and Y → Z, but Y does not determine X. Here Z is transitively dependent on X through Y. Example: if EmployeeID → DepartmentID and DepartmentID → DepartmentName, then DepartmentName is transitively dependent on EmployeeID. Transitive dependencies cause 3NF violations.",
    "Update anomalies are problems caused by redundancy in a poorly designed relation. An insert anomaly occurs when a fact about one entity cannot be stored without also storing a fact about another unrelated entity. An update anomaly occurs when a single real-world fact is stored in multiple rows, so changing it requires updating all rows to avoid inconsistency. A delete anomaly occurs when deleting one entity accidentally destroys information about another entity.",
    "Boyce-Codd Normal Form (BCNF) is a stricter version of 3NF. A relation is in BCNF if, for every non-trivial functional dependency X → Y, X is a superkey (i.e., X functionally determines all attributes of the relation). BCNF eliminates all redundancy due to functional dependencies. Most relations in 3NF are already in BCNF; violations only occur when there are multiple overlapping candidate keys.",

    # Concurrency Control and Isolation Levels
    "Concurrency problems arise when multiple transactions execute simultaneously and access the same data. The four classic concurrency anomalies are: Lost Update (one transaction overwrites another transaction's committed update, causing the earlier change to be lost.), Dirty Read (a transaction reads data written by an uncommitted transaction that later rolls back), Non-Repeatable Read (a transaction reads the same row twice and gets different values because another transaction modified it in between), and Phantom Read (a transaction re-executes a query and finds new rows because another transaction inserted or deleted data in between).",
    "Locking is the primary mechanism for concurrency control. A Shared Lock (S-Lock / Read Lock) allows multiple transactions to read an object simultaneously but blocks any write. An Exclusive Lock (X-Lock / Write Lock) gives a single transaction exclusive access for writing; all other reads and writes are blocked. A transaction must acquire the appropriate lock before accessing data and releases it when done.",
    "The Two-Phase Locking Protocol (2PL) guarantees serializability. It consists of two phases: the growing phase, during which a transaction may acquire locks but not release any; and the shrinking phase, during which a transaction releases locks but may not acquire any new ones. Once the first lock is released, no new lock can be acquired. 2PL prevents many concurrency anomalies but can cause deadlocks.",
    "A deadlock occurs when two or more transactions are each waiting for the other to release a lock, so none can proceed. Example: Transaction T1 holds a lock on table A and wants table B; Transaction T2 holds a lock on table B and wants table A. Deadlocks are detected (e.g. by a wait-for graph) and resolved by aborting one of the transactions (the victim) and rolling it back.",
    "SQL transaction isolation levels define how much a transaction is isolated from the effects of other concurrent transactions. READ UNCOMMITTED: dirty reads, non-repeatable reads, and phantom reads are all possible. READ COMMITTED: dirty reads are prevented; non-repeatable reads and phantom reads are possible. REPEATABLE READ: dirty and non-repeatable reads are prevented; phantom reads are still possible. SERIALIZABLE: all three anomalies are prevented; transactions behave as if executed one at a time. Set with: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE.",
    "Optimistic concurrency control assumes conflicts are rare and does not lock data during reading. Each row has a timestamp or version number. When a transaction writes, it checks whether the timestamp has changed since it last read the row. If it has changed (another transaction modified the row), the current transaction is aborted and must retry. Optimistic locking suits workloads with many reads and few write conflicts. Pessimistic locking acquires locks immediately and holds them, which is safer under high-conflict workloads.",
]
